### ISSUE TITLE
mesos-rxjava and rxclojure

### ISSUE THREAD

**Issue by gonewest818** [funcatron/mesomanager#1]
I notice you aren't using mesos-rxjava for tron...  and here it seems you started but then didn't proceed. Is there a particular reason you didn't continue down this path?

**Comment by dpp** [comment]
Development priorities... it'll happen (adding/removing instances via mesos-rxjava), but we've gotta finish higher priorities first.

**Comment by dpp** [comment]
Also, the code is going to live in https://github.com/funcatron/tron which may get rolled up into the main Funcatron repo...

Please close the issue if this answers the question.
